### ISSUE TITLE
RFC Serverside graphql query caching

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-graphql#164]
Related to https://github.com/silverstripe/silverstripe-graphql/issues/130 (schema caching)

# Use case

When generating responses for DB intensive queries it can be necessary to cache to prevent repeated overhead cost. The challenge is that the query controller doesn't immediately know how to invalidate / validate caches.

# Options

There are two main approaches that could be taken, each with a similar difficulty in their approach:

 - Caches automatically invalidate based on the modified date of the records that back them. The challenge is that graphql queries don't always naturally map strictly to dataobject types, although specific parts of a query response can.
 - Caches are explicitly cached on write of a specific model. This requires user logic (or otherwise a reasonably smart onAfterWrite extension) to trigger invalidation of the query. The inverse of the above is the issue here; Given a model, there's no explicit knowledge of which queries should be invalidated.

# Suggestion

Given that queries are more complex than the underlying data model, my suggestion is to look at the former, where we develop a stronger knowledge of what models back a query. This could be done one of two ways:
 - Static analysis of the query, where we traverse the query on each request to extract the metadata on demand. cc @unclecheese to expand on this idea. :)
- On cache-miss, whenever a record type is queried we register this on the graphql controller / type, so that when the cache response is saved to the cache, we additionally have a list of classes (and perhaps other metadata) that we can include in the cached value. Since this is only done on cache-miss, a cache-hit can extract this from the cache itself rather than performing static analysis, and can do post-hit validation to see if any of the models have been modified since the cache was created.

Pseudocode:

```php
$key = md5($query) . '-' . var_export($args, true);
$cached = $cache->get($key);
if ($cached) {
   foreach ($cached['classes'] as $class) {
      if (DataObject::get($class)->max('LastModified') > $cached['date']) {
        $cached = null; // class modified, fail validation of cache
        break;
      }
   }
}
if (!$cached) {
   $response = $manager->respond($query, $args);
   $classesUsed = $manager->getClassesUsed();
   $cache->save($key, ['response' => $response, 'classes' => $classesUsed, 'date' => DBDateTime::now()->getValue()]);
}
return $response;
```

Whenever a type would perform a query, it would need to register any class it used. Otherwise, we could "hook" into dataquery with an extension and spy on classes queried during that time.

**Comment by tractorcow** [comment]
Pseudocode with spy enabled.

```php
$key = md5($query) . '-' . var_export($args, true);
$cached = $cache->get($key);
if ($cached) {
   foreach ($cached['classes'] as $class) {
      if (DataObject::get($class)->max('LastModified') > $cached['date']) {
        $cached = null; // class modified, fail validation of cache
        break;
      }
   }
}
if (!$cached) {
   $spy = ClassSpyExtension::singleton();
   // Closure begins / ends recording of classes queried by DataQuery.
   // ClassSpyExtension is added to DataQuery via yml
   list ($classesUsed, $response) = $spy->recordClasses(function() {
       return $manager->respond($query, $args);
    });
   $cache->save($key, ['response' => $response, 'classes' => $classesUsed, 'date' => DBDateTime::now()->getValue()]);
}
return $response;
```

**Comment by stevie-mayhew** [comment]
Would it be worth looking at this from the perspective of minimal viable work first, allowing caching mechanisms to be defined in configuration and injecting that configuration into the graphql endpoint and then look at introspection of used classes at a later date and as a possible upgrade pathway? I'm concerned that the ability to configure the cache mechanism wouldn't be available apart from through a code pathway which would limit its feasibility for some use cases i.e. 
 - I want to cache this forever no matter what and break it myself through some mechanism in the CMS
 - I want to cache this only for certain users so they get different results but we retain a cache for it
 - I want to cache this based on the location which the request is coming from

This could be fairly simple to define based on the post query sent (or not simple as the case might be...)

Psuedo:
```yml
SilveStripe\GraphQL\Manager:
  cache:
    ListQueryOne:
      query: '"{ basicFields: readFilters(ListType: "One",) { edges { node { ID Title } } } }"
      contains: 
        - ListDataObject
      expires: +2 days
    ListQueryTwo:
      query: '"{ basicFields: readFilters(ListType: "Two",) { edges { node { ID Title } } } }"
      contains: 
        - ListDataObject
        - MoreAdvancedListTypeObject
      expires: +12 days
```
// SilverStripe\GraphQL\Controller.php
```php
    $manager = $this->getManager();
    list($query, $variables) = $this->getRequestQueryVariables($request);
    if ($manager->getCached($query)) {
        // etc
    }
```

Then the `getCached()` call would be similar to what has been proposed above.

This idea is based upon the work done by camspiers  in https://github.com/heyday/silverstripe-cacheinclude#cache-block-config

**Comment by tractorcow** [comment]
>  I'm concerned that the ability to configure the cache mechanism wouldn't be available apart from through a code pathway which would limit its feasibility for some use cases i.e.

As with most "addon logic" I'm looking at making this caching an isolated middleware, and allowing garphql manager to accept any middleware-injected classes. You should be able to swap this out / nest as necessary on a per-project basis.

**Comment by tractorcow** [comment]
We could make it YML injected, as well as allowing it to be injected into the operations directly. It may be more robust to set it on a per-class basis rather than doing string matching. There are a huge number of possible string permutations for each query, and you'll run into the risk of edge cases bypassing cache.

E.g.

```php
public function provideGraphQLScaffolding(SchemaScaffolder $scaffolder)
    {
        $scaffolder
            ->type(Post::class)
                ->addFields(['ID', 'Title', 'Content'])
                ->operation(SchemaScaffolder::READ)
                    ->setCacheAge(3600) // 1 hour 
                    ->end()
                ->end();

        return $scaffolder;
    }
```

**Comment by tractorcow** [comment]
Proof of concept at https://github.com/silverstripe/silverstripe-graphql/pull/166

**Comment by tractorcow** [comment]
Next step is to improve cache-control so that we can set specific expiry times as well as other cache validation / breaking (instead of ONLY dataobject LastEdited).

**Comment by chillu** [comment]
Awesome work Damian, really cool to see these in depth contributions continuing :)

There's two ways to add caching hints:

 * Static/declarative via schema types (see Stevie's example)
 * Dynamic via resolvers (Damian's implementation)

Damian's approach is dynamic, but via the GraphQL module logic, not on a resolver level. This leads to a solution which assumes assumes *one* cache entry per query response. That's a very RESTy way to think about API responses, and works well with traditional HTTP caching layers if sending the right HTTP headers based on this info. 

But in GraphQL, you can combine infrequently with frequently changing data types, which can lead to under-caching if treated naively. The emerging [Apollo Cache Control Standard](https://github.com/apollographql/apollo-cache-control) tries to solve this in a more declarative way, giving smart middleware services outside of the application (Apollo Engine) enough metadata to maximise cacheability in a fast layer. See [Apollo Response Caching](https://www.apollographql.com/docs/engine/caching.html) for details.

I think most SilverStripe uses will be well served by Damian's implementation (single cache key and max age), particularly since further object caching can be implemented in custom resolvers. At the moment, smart GraphQL middleware services like Apollo Engine are a fringe use case, but I can see these becoming more popular for high throughput (readonly) APIs with a lot of variation in query signatures (e.g. public APIs rather than single use).

In terms of creating APIs like `setCacheAge()` though, we should keep this on a field rather than "operation" level. Remember that each query in GraphQL is just a field on the `Query` type, which can contain further nested fields. And ideally we follow the Apollo conventions for naming. Caching on a field level wouldn't fit the `QueryMiddleware` concept, it'd be more like a `ResolverMiddleware`. Each resolver gets a `$context` object already to accumulate this detail through custom code. Could we wrap resolver execution with a similar middleware concept, and have the `QueryMiddleware` just look at the resulting `$context` info?

Aside: It'll be a bit harder to retain the "query recorder" principles if we introduce eager loading of relationships through database joins into our ORM (e.g. has_one) - but that's just a theoretical rather than practical concern.

**Comment by chillu** [comment]
Summary of a discussion with @tractorcow:

 * Agree to not supporting two caching approaches in the module. 
 * Middleware is useful in it's own right, even if caching moves to resolvers. Damian to trim down PR to just middleware, without caching implementation
 * Resolver-based caching needs to decorate/proxy both scaffolded and custom resolvers (through `setResolver(<class>)` and `setResolver(<instance>)`. The underlying library doesn't provide generic hooks for this (see related [tracing discussion](https://github.com/webonyx/graphql-php/issues/289#issuecomment-399633709)).
 * The easiest way to decorate/proxy resolvers is through DI and factories in our own code (through  `Object::create()`). There's some potential for driving a library API addition and making this a generic module
 * Need more thought around how cached resolver values can signal that nested fields need to be evaluated at runtime (contain their own cached values with potentially different expiry logic)
 * Since resolvers return can [return array or Traversable types](http://webonyx.github.io/graphql-php/type-system/lists-and-nonnulls/), we need to figure out how to serialise these safely for caching. Damian raised that `SS_List` might have trouble being consistently serialised.
 * We're keen to hear @unclecheese thoughts on this before taking it much further

**Comment by chillu** [comment]
@tractorcow Thanks for trimming down your pull request at https://github.com/silverstripe/silverstripe-graphql/pull/166. Is there a way for you to expose the middleware implementation on top of that, for future reference? My assumption is that you're moving this to custom project code, which is fine. But the RFC discussion so far revolves around your approach, so would be good to keep it in a gist. As a baseline for a more generic (hopefully resolver based) approach.

**Comment by chillu** [comment]
I'm keen to get traction on this again. @tractorcow I'm assuming that your current approach wouldn't need resolver-based caching, and you're planning to keep your implementation is project code, so we'd likely take this on with the product team here.

Proposed acceptance criteria:

 * As a developer, I can customise caching behaviour in GraphQL in order to achieve fast response times 
 * There's built-in support for `LastEdited` based caching. It can be easily set alongside other YAML GraphQL configuration for a specific type
 * The built-in `LastEdited` caching takes GraphQL query parameters into account to avoid inaccurate cache values between queries
 * The built-in `LastEdited` caching applies for a specific type regardless in which query the type is used.
 * The built-in `LastEdited` caching takes HTTP authentication headers into account by default to avoid exposing data without permission checks
 * Custom caching logic can be configured within a resolver implemetation
 * All cacheable data types are stable when serialised and unserialised (incl. `SS_List`)
 * Resolver results can be nested. It is possible to embed uncached values from a child resolver in the cached value of a parent resolver
 * There is documentation for implementation custom resolver caching logic

**Comment by tractorcow** [comment]
> Since resolvers return can return array or Traversable types, we need to figure out how to serialise these safely for caching. Damian raised that SS_List might have trouble being consistently serialised.

Yes graphql had some issues with object-based response types, which I had to adjust with lazy-serialisation on middleware response. Handling resolver based responses will have a similar problem, and likely similar solution.

The SS_List -> array serialisation occurs in DataObjectScaffolder::createFields() (See $resolver) where it maps list of objects to arrays. We may need to strip that out into lazy-serialisation, such that resolver doesn't fail on already resolved responses in an idempotent way.
