### ISSUE TITLE
Arbitrary queries error returns _toString() must return a string

### ISSUE THREAD

**Issue by gorriecoe** [silverstripe/silverstripe-graphql#189]
I get this error: `Catchable  fatal error: Method GraphQL\Language\AST\FieldNode::__toString() must  return a string value in  /var/www/vendor/silverstripe/framework/src/Dev/Backtrace.php on line 178` when using the following the example set in [Adding arbitrary queries and mutations](https://github.com/silverstripe/silverstripe-graphql#adding-arbitrary-queries-and-mutations).

```php
$scaffolder
    ...
    ->query('latestPost', Post::class)
        ->setUsePagination(false)
        ->setResolver(function ($object, array $args, $context, ResolveInfo $info) {
            if (singleton(Post::class)->canView($context['currentUser'])) {
                return Post::get()->sort('Date', 'DESC')->first();
            }
        })
        ->end()
```

I not able to figure out the trace on this and am starting to wonder if the issue is in silverstripe-graphql.  Any help would be appreciated

**Comment by robbieaverill** [comment]
Hey @gorriecoe, we patched this in the upstream library a while back in https://github.com/webonyx/graphql-php/commit/c962afc56611c3e953bc0ac1bcdca3a5241d33ac

I think it's caused by recursive backtracing when you have an error. Perhaps you could pull in that (unreleased) graphql-php commit to try and help you work out what's not working in your code.

I don't think there's a fix in this repository for it, so I'm going to close for now =) cheers!

**Comment by gorriecoe** [comment]
Hey @robbieaverill, silverstripe-graphql requires webonyx/graphql-php: "~0.8.0".  I think it should be "~0.8" not "~0.8.0".  The extra zero with the tilde means it will only increase the patch number.

**Comment by robbieaverill** [comment]
I'm not sure it would be safe for us to allow new enhancements to be pulled in by this dependency. Nevertheless, the library is up to 0.12 now so we should update the constraint and test it with that in palce

**Comment by gorriecoe** [comment]
I would assume if they are using semver than it wouldn't be any breaking changes.

**Comment by ScopeyNZ** [comment]
Unfortunately while the major is 0 semver allows breaking changes in minors 🙁

**Comment by robbieaverill** [comment]
We can discuss upgrading the underlying library further in https://github.com/silverstripe/silverstripe-graphql/issues/186

**Comment by michalkleiner** [comment]
Just hit the same issue — enforcing string returned from the underlying method makes it fail silently, but the issue is with some recursion in the hierarchy that's trying to be json_encoded, `json_last_error_msg()` returns `Recursion detected`, so possibly some normalisation needs to be done prior encoding?

**Comment by ScopeyNZ** [comment]
Hey @michalkleiner . This is an issue in the underlying library. It'd be an issue as soon as your GraphQL schema is a certain size (in terms of depth). Perhaps if you feel strongly about this being an issue we can discuss it on an issue on that library repo?
