### ISSUE TITLE
Scaffolded read operations don't check canView on returned list

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#211]
They only check canView on the singleton, not the actual results. That's inconsistent with developer assumptions around what scaffolding should provide. Given it partially applies canView already, I don't think this is a semver breakage, but rather a bugfix for a partial implementation.

It should use batching mechanisms if possible via `InheritedPermissions->batchPermissionCheck()

# PR's

- [ ] https://github.com/silverstripe/silverstripe-graphql/pull/222

**Comment by chillu** [comment]
* The PRs only apply to `ReadOne`. The `Read` implementation does checks differently: Instead of checking the first result item, it checks a singleton before querying.
 * Both approaches are incomplete at best: `canView()` on a singleton might return false even if it returns true on all records (depending how it's been implemented). 
  * Both approaches differ from virtually any other place where we implement permission checks: `GridField`, `SearchForm`, `ReportAdmin`.

I can see why this has been done: Enforcing `canView()` means turning a lightweight `DataList` into a concrete `SS_List` with a whole bunch of unbounded queries. The limits are done in `Connection`, which calls resolvers like `Read` via it's `$connectionResolver`. That happens *after* this resolver executes, at which point permissions enforced in that resolver would have produced an unbounded SS_List already. 

I think we need to remove the permission checks from the CRUD scaffolders returning a list (e.g. `Read`), and make that the responsibility of the `ListQueryScaffolder` and `ItemQueryScaffolder`. This would also allow creating custom resolvers without requiring (error prone) reimplementation of permission checks.

Here's the sequence of classes involved in creating those resolvers. It illustrates why it's hard to put this in any other layer than the top level.

 * Item resolver: `ItemQueryScaffolder, ReadOne`
 * Paginated list resolver: `ListQueryScaffolder, PaginationScaffolder, Connection, Read`
 * Unpaginated list resolver: `ListQueryScaffolder, OperationScaffolder->createResolverFunction, Read`

**Comment by ScopeyNZ** [comment]
Part of the reason for our recent `readOne` patch is because it was not following the old `GridFieldDetailView` logic which utilises `canView`. This probably shows an issue with `canView` on models in general - they're completely free to do permission checks on any wild whim (`if (rand(0,5) === 5) return true;`). Having permission checks at the `ItemQueryScaffolder` level will not allow us to utilise `canView` on a specific model from the database IIRC.

**Comment by chillu** [comment]
> they're completely free to do permission checks on any wild whim

Yep, but we're not going to fix that as part of this issue - it's a very core part of how SilverStripe operates, which unfortunately has some wide ranging performance implications.

> Having permission checks at the `ItemQueryScaffolder` level will not allow us to utilise `canView` on a specific model from the database IIRC.

I'm not sure I understand. You mean that you can't batch `SELECT` statements for the database-backed aspects of permissions on some models?

**Comment by ScopeyNZ** [comment]
Like my `canView` method checks some database property. 
```
public function canView() {
    return $this->MySpecialProperty > (int) static::config()->get('special_requirement');
}
```

How can the `ItemQueryScaffolder` resolve the right permission in this case? It needs to call `canView` per item in the DataList (or just on the already resolved item in a `readOne` query)

This was exactly the case that prompted us to make that patch to `readOne` - the state of the specific object (element from elemental) in the database affected its permissions - but it was broken since we started using GraphQL for the UI.

**Comment by unclecheese** [comment]
Pretty sure this is closed by https://github.com/silverstripe/silverstripe-graphql/pull/222

**Comment by unclecheese** [comment]
https://github.com/silverstripe/silverstripe-graphql/pull/222 has been merged. closing.
