### ISSUE TITLE
error appends junk into graphql json output

### ISSUE THREAD

**Issue by mikeyc7m** [silverstripe/silverstripe-graphql#257]
got an issue where the graphql returns a valid successful result, however something has appended an error message to the output, invalidating the JSON. See here:
`
{"data":{"createToken":{"Token":"...etc","Member":{"...etc"},"__typename":"MemberToken"}}}[2020-03-31 11:39:25] manifestcache-log.WARNING: Failed to save values {"keys":["__CACHE__"],"exception":null} []`

why are we seeing a manifestcache-log error message appended to a JSON string?

**Comment by robbieaverill** [comment]
Which versions are you running? Do you have any custom loggers configured?

**Comment by mikeyc7m** [comment]
we're on SS framework 4.3.1
we've branched from graphql 3, not sure how to find the root
i've since added a custom logger to suppress the error message, but it ignored it

**Comment by mikeyc7m** [comment]
manifestcache-log is something to do with how all the php classes are cached by the framework. for whatever reason it hit a snag and decided to dump the error into the graphql output.
it can be seen when logging into the cms, all the graphql-dependent feature are broke, such as searchforms, filesystem etc.
i can appreciate that the error needs to be exposed somewhere, but dumping it on the end of a valid JSON response is just rude!

**Comment by robbieaverill** [comment]
I suspect this might be caused by a lack of logging handlers being defined, so perhaps monolog dumps to stdout or the end of the response stream. I need to validate this theory though. We changed some logging configuration in 4.4.0 which might be related, the default logger is now for user defined logging rather than core. I’ll take a look and get back to you.

**Comment by robbieaverill** [comment]
Do you have silverstripe/fulltextsearch installed as well?

**Comment by mikeyc7m** [comment]
We're on SS platform so I'm limited in what I can see, redeployment is very time-consuming.
I can't share a customer's lockfile. Their site is dead because of this ridiculous non-issue!
We're not using any SS_ERROR_LOG value.
FullTextSearch is installed, 3.4.1
Searching the core code, symfony's AbstractCache tries to log this specific error to a logger, but I'm guessing it doesn't know any, so it just dumps into standard output, which just happens to be the graphql response.

**Comment by robbieaverill** [comment]
Ok, if you’re using SSP then I’d suggest you go through their prioritised support channel

**Comment by maxime-rainville** [comment]
Looking at the code for `ManifestCacheFactory`, it looks like the error will only be logged to PHP standard output if you're in Dev mod. https://github.com/silverstripe/silverstripe-framework/blob/dcd54ecec025b3d024b8757bb8855ef1e610ed4c/src/Core/Cache/ManifestCacheFactory.php#L21-L34

If this is a production site, maybe double check it is not running with `SS_ENVIRONMENT_TYPE="dev"`.

**Comment by mikeyc7m** [comment]
hmm we were seeing the opposite, in that all our dev mode environments did not have the issue, but only our live production site did. but maybe robbie is right too, it could be an issue with ssp not setting the environment correctly. so i did a full redeployment and it's behaving for now.

regardless, any message should not be appended to a JSON response.

**Comment by mikeyc7m** [comment]
This issue was resolved by adding a SyslogHandler logger - my colleague insists every SSP deployment should include one! It allows these sorts of low-level warnings to be dumped into Graylog instead of standard output.

**Comment by mikeyc7m** [comment]
Although I've closed the issue, the underlying bug remains - the graphql should be better protected from junk appending to the end of the JSON.

**Comment by asecondwill** [comment]
I'm getting this error too.  I thought it was due to permissions or something but it's that I have to set up a SyslogHandler ?  where is how to do that and the requirement documented?

**Comment by robbieaverill** [comment]
@asecondwill you can find the logging documentation here: https://docs.silverstripe.org/en/4/developer_guides/debugging/error_handling/

**Comment by lekoala** [comment]
I have the same issue, this is not a sane default behavior, even in dev mode
i get plenty of errors like this
manifestcache-log.WARNING: Failed to save values: rename ...

first, i'm not sure why the cache fails in the first place, second, adding to std output doesn't make a lot of sense

**Comment by mikeyc7m** [comment]
Hmm we're still seeing comments on this issue... if you're on SS Cloud, they have documented the setup required here:
https://servicedesk.silverstripe.cloud/support/solutions/articles/75000012848-server-logs
You need to route these stray messages back into the logger. Here's the code from their documentation:
```---
Name: sysloglogging
---
SilverStripe\Core\Injector\Injector:
  Psr\Log\LoggerInterface:
    calls:
      pushSilverStripeSyslogHandler: [ pushHandler, [ '%$Monolog\Handler\HandlerInterface.silverstripe' ] ]
  # Internal error handler, piped to syslog which is routed to Graylog
  Monolog\Handler\HandlerInterface.silverstripe:
    class: Monolog\Handler\SyslogHandler
    constructor:
      - 'SilverStripe_log'
```

**Comment by lekoala** [comment]
thanks but I'm not sure that will fix anything ?

If I get it correctly, we have BaseKernel::buildManifestCacheFactory that is building a ManifestCacheFactory (not using injector, its new ManifestCacheFactory, not ManifestCacheFactory::create). Therefore, it is using the default logger (StreamHandler on dev, ErrorLogHandler otherwise) when building the cache class.
there is not much you can change to that in yml : if you have an issue, it will use the StreamHandler in dev regardless.

Of course, i can implement my own cache factory but that seems a bit counterproductive :-) (and even then, it won't fix any issue happening between the regular instantiation and the ::create calls)

Maybe i should fix the root cause but that's another topic, ie : why do i get stuff like 

manifestcache-log.WARNING: Failed to save values: rename(...\configcache\c82ed87ee4f8,
...\configcache\U\F\QAdjY48zDlbAQWHpYUrw): Access is denied(code: 5)
(edit: it seems linked to xdebug on windows, updating it has fixed the issue so far)
