### ISSUE TITLE
GraphQL 4: Query caching middleware

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#274]
We should revisit [Damian's query caching middleware](https://gist.github.com/tractorcow/fe6571d2d00340a311ca31a677a05a29) done as a POC a couple years ago. It still has relevance today and is largely compatible with the new API.

Could flag it as `experimental_queryCaching` middleware and see how it improves performance in the CMS, etc. just to get some uptake.

**Comment by chillu** [comment]
Yeah I'd be OK with adding it as experimental, which would also allow us to cover it with some unit tests. Because in the end, even though it's experimental, any caching implementation has the potential to cause security incidents, which is why I see us providing this a bit more binary. If its part of the module, a customer being affected by data leaks will argue that the fault lies with the module. If it's just a bit of code on a developer's gist which another developer adapted for a specific project, it's a bit easier to change this expectation. ;tldr: You can't half-ass security-related features.

**Comment by unclecheese** [comment]
Implemented here: https://github.com/silverstripe/silverstripe-graphql/pull/266/commits/cedacb79929745bd1d49bf9309e68c7679c7a90e

Docs here: https://github.com/silverstripe/silverstripe-framework/pull/9652/commits/996141de189a11264f5387c091f666ee104de2b1
