### ISSUE TITLE
GraphQL 4: DBField default args

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#275]
The default dataobject resolver accesses by `obj()` by default, which means we have some insight about what methods might be available on those DBFields to modify their output. These could be expressed as default args. 

Some ideas:

```
myDate(format: String)
myText(limitCharacterCount: Int, limitWordCount: Int)
myCurrency(nice: true)
```

etc...

Could be a monolithic plugin that just handles them all by switch statement, or something.

**Comment by chillu** [comment]
I think it'll be important to whitelist those per `DBField`. And I'd err on the side of starting with an empty whitelist, because all the examples you've shown here are presentational, and can be better achieved on the client. `limitCharacterCount` could be regarded as a way to reduce response size, but I'm not sure how necessary that is in practice. Even for `DBHTMLText`, when would you *not* want shortcodes to be resolved for you in API payloads?

**Comment by unclecheese** [comment]
Yeah, I don't see this as being introspective at all. I think we just look at the APIs for all these DB fields and pick and choose what would make sense as an argument. But if some module comes long and adds a new method, then you're on your own for adding a new arg to the fields that use it. This is a really dangerous rabbit hole if we make it too magic.

**Comment by unclecheese** [comment]
Closing as PR has been merged.
