### ISSUE TITLE
Expose type (different from __typename)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#312]
Due to our usage of `_extends` over unions/interfaces, we can't rely on `__typename` to identify the "implicit type" (see lots of reasons over at https://github.com/silverstripe/silverstripe-graphql/issues/209).

I'm proposing that we add a new `_modelType` attribute which contains the *short* name inferred from the PHP class name. Using "model" in the name ensures some relation to the YAML config (`models` section) and distinguishes it from the GraphQL type concept. Using the short name rather than the PHP classname provides a baseline of decoupling from the PHP implementation.

It's not great, one of the tradeoffs in choosing Option B over Option C or Option D in https://github.com/silverstripe/silverstripe-graphql/issues/209

```graphql
query readPages {
  __typename
  _modelType
  id
  _extend {
    errorPage {
      errorCode
    }
  }
}
```

```json
[
  {
    "__typename": "Page",
    "_modelType": "ErrorPage",
    "id": 123,
    "_extend": {
      "errorPage": {
        "errorCode": 404
       }
    }
  }
]
```

**Comment by blueo** [comment]
I agree this would be quite useful for handling these queries on the JS side. You can then easily select the type you are looking for rather than validate each type to see what you have. Might also prevent a situation where you change the type of a an object and you end up with records in two tables (not 100% sure if that is possible)

**Comment by unclecheese** [comment]
No longer relevant with the new extension by interfaces pattern.
