### ISSUE TITLE
GraphQL 4: Controller constructor is too greedy

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-graphql#351]
Seems like the `Controller` class requires parameters that aren't necessarily depedencies.

* schemaKey (string): Mostly done for the ergonomics of the config layer. It's annoying that you can't pass a first-class `Schema` instance. But for that matter, the only method that _requires_ a schema is `index()`. (introspectTypes is a weird one.. that [probably be done away with](https://github.com/silverstripe/silverstripe-graphql/issues/270)

* `schemaConfig` (SchemaConfig): Not sure what the use case is here, since `Schema` can be composed with a `SchemaConfig` instance anyway.

Recommend:

* Only have optional `schemaKey` param, call new public `setSchemaByKey` method
*  Throw on index when no schema set
* If `Schema` has no `SchemaContext` passed to it, automatically try to set it from the store. It's getting too confusing to know the difference between `$schema->getContext()` and `$schema->getStore()->getContext()`.

**Comment by chillu** [comment]
> the only method that requires a schema is index()

That's the *main purpose* of this class though, so I'd say unless we infer this from the request context, declaring this requirement in the constructor is correct. It makes controllers harder to test that it takes charge of creating its own `Schema` instance.

> If Schema has no SchemaContext passed to it, automatically try to set it from the store.

`CodeGenerationStore` doesn't have a reference to a `SchemaStore`. Do you mean `Schema`? In which case I agree that we should remove the default creation of a context from `Controller::__construct()`, because it already happens in `Schema::__construct()`.

**Comment by unclecheese** [comment]
This was cleaned up in 4.0.0-alpha1 https://github.com/silverstripe/silverstripe-graphql/releases/tag/4.0.0-alpha1
