### ISSUE TITLE
Use MemberAuthenticator by default

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#61]
The README states the following:

> If you are logged into the CMS and performing a request from the same session then the same Member session is used to authenticate GraphQL requests, however if you are performing requests from an anonymous/external application you may need to authenticate before you can complete a request.

This is inaccurate, since with the recent authenticator changes, the session based authenticator is no longer configured by default. It should be, in order to allow `graphql-devtools` to actually work (through `/dev/graphiql`). We could consider adding `MemberAuthenticator` into the devtools module instead, but it seems a bit weird to have the presence of a dev tool influence the authentication capabilities of are core API

**Comment by robbieaverill** [comment]
I don't think that the dev tools module _should_ have its own authenticator, unless it's for testing something.

If MemberAuthenticator is bundled with this module by default but not enabled, perhaps we just need to enable it somewhere like asset-admin by default?

**Comment by robbieaverill** [comment]
I think that the MemberAuthenticator *is* configured by default, as is the BasicAuthAuthenticator ([see here](https://github.com/silverstripe/silverstripe-graphql/blob/master/src/Auth/Handler.php#L23-L41)). The BA authenticator would kick in if it is applicable, e.g. that the basic auth credentials are passed.

The MemberAuthenticator is active, but returns false because the request from `/dev/graphiql` to `/graphql` cannot resole the current session state, so `MemberAuthenticator::isApplicable` returns false.

**Comment by PapaBearNZ** [comment]
I had to manually add BA into my graphql yaml config.  I don't think it is
configured for GraphQL out of the box.  For me the Member Authenticator
didn't work.  Until I configured BA I got permissions errors all the time.

Kind regards

James Pluck
-- 
M: +64-21-236 6900
E: james@courage.co.nz

**Comment by robbieaverill** [comment]
Hey @PapaBearNZ - it's a little confusing. Not sure which version you're using, but I assume it's the most recent.

The graphql-devtools was not sharing the CMS session in its XHR requests. This is fixed in silverstripe/silverstripe-graphql-devtools#2

Both `MemberAuthenticator` and `BasicAuthAuthenticator` are _configured_ by default, and both are checked (`isApplicable`). In the case of the browser-based GraphiQL tool, the issue above was preventing the `MemberAuthenticator` from returning `isApplicable()` = `true`. Basic authentication doesn't work in the browser based GraphiQL tool (without a browser plugin to add custom headers anyway), so neither authentication method would have been working from that tool.

From the GraphiQL standalone app the `MemberAuthenticator` will never work because it cannot share the browser session. The `BasicAuthAuthenticator` should be used in this instance.

**Comment by PapaBearNZ** [comment]
Thanks for the update, Robbie.  I'll update my graphql-dev-tools.  I
eventually found a Chrome wrapper plugin that allowed me to configure the
header tags to do BA.  It's called GraphIQL Feen and you can find it here
if you want to take a look.

https://chrome.google.com/webstore/detail/graphiql-feen/mcbfdonlkfpbfdpimkjilhdneikhfklp



Kind regards

James Pluck
-- 
M: +64-21-236 6900
E: james@courage.co.nz
