### ISSUE TITLE
Make CORS configurable

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-graphql#66]
GraphQL APIs will be consumed by third party apps on other hosts, e.g. sending XHR requests from your custom web app to a centralised SaaS solution running a SilverStripe-powered GraphQL endpoint. This requires [Cross Origin Resource Sharing](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing)

See https://github.com/colymba/silverstripe-restfulapi/blob/master/doc/RESTfulAPI.md#cors for an example.

**Comment by PapaBearNZ** [comment]
First draft of patch for this issue is up on my fork [https://github.com/PapaBearNZ/silverstripe-graphql](https://github.com/PapaBearNZ/silverstripe-graphql/blob/feature/scaffolding/src/Controller.php)

Patch adds Yaml config for CORS to the graphql module.  Also adds a check for the pre-flight OPTIONS request, and if CORS is enabled, adds the appropriate headers to the response object - both for the OPTIONS response and for the actual data response.

No unit tests as yet.  

Looking for suggestions and comments on improvements.

**Comment by chillu** [comment]
Looks great :) A few comments:

 * `processCorsConfig()` would be better named as `getCorsResponse()`
 * Do you require
 * Can you add this to the README please? :)
 * Needs default YAML config
 * Should default to an empty string for `Allow-Origin`, so we don't inadvertendly open up installs to the world via `*`
 * `Access-Control-Allow-Headers` should only contain `GET` and `POST`. The other REST verbs aren't happed for GraphQL
 * The `86400` default should be in the default YAML config, not hardcoded in the logic

I've fixed the 301 redirect, see https://github.com/silverstripe/silverstripe-installer/pull/152/

**Comment by PapaBearNZ** [comment]
Thanks Ingo.  

Regarding the allow headers . I think we still need the OPTIONS method as well.  Otherwise won't the request bounce?

Understood about the YAML default config and I agree with the suggestion of defaulting to denied rather than open.  I used '*' because that's what the REST module used but denied is a safer default.  I'll make the appropriate changes and hopefully have a PR ready later today.

Thanks for the work on the redirect issue.  I'll update and test that.

Regarding the README - no problem there. However, the docs are getting pretty big.  Is this going to be updated and pushed to docs/en?

**Comment by PapaBearNZ** [comment]
#69 PR submitted.

**Comment by tractorcow** [comment]
Looks like this was fixed with #69 not sure why it's still open.
