### ISSUE TITLE
Inconsistent naming in scaffolder

### ISSUE THREAD

**Issue by flamerohr** [silverstripe/silverstripe-graphql#95]
This is actually unnoticeable if you keep your DataObject name and table_name the same.
But once you start moving away from it (e.g. namespace a table name) it gets really funky.

I'll have a `readTransactions` which is great, what I wanted :D
But then I'll have an `updateMyPrefix_Transaction`... umm, not what I'd have expected.

A few options available:
- Use the DataObject's plural/singular consistently
- give us the config setting to define a plural/singular noun
- Use the DataObject's table_name consistently

## Pull Requests: 
- [ ] https://github.com/silverstripe/silverstripe-graphql/pull/143
- [ ] https://github.com/silverstripe/silverstripe-versioned/pull/134

**Comment by robbieaverill** [comment]
>Use the DataObject's plural/singular consistently

This could contain spaces, punctuation etc

Perhaps you could use what's in place already, but remove the configured default table separator (`_`) with a string replacement call?

**Comment by flamerohr** [comment]
Yeah, that's a good point

Maybe a config plural/singular would be the cleaner approach :D

**Comment by chillu** [comment]
Yeah this is a bit messy.

```
<?php
namespace MyPrefix;

class MyDataObject extends DataObject {

	private static $singular_name = 'Data Object';

	private static $plural_name = 'Data Objects';
}
```

Currently returns:

 * Type: `Data_Object`
 * Query: `readDataObjects()` with `readDataObjectsConnection`, `readDataObjectsEdge`
 * Mutations: `updateData_Object()` with `Data_ObjectUpdateInputType`, `deleteData_Object()`

I think we shouldn't rely on `singular_name` and `plural_name`, since they might be different (e.g. "Campaign" vs. "ChangeSet") in a way that sometimes doesn't make sense for devs. Those names are for the CMS UI, not for its API surface. They might change as the business language changes, but that shouldn't affect the underlying class nomenclature. We don't use singular_name in the ORM either.

In terms of pluralisation, I'd just apply the same three lines from `DataObject::plural_name()` in the scaffolder, and allow people to override the operation names.

@unclecheese @flamerohr Thoughts?

Moving this up in the backlog since it's technically an API change, sigh.

**Comment by flamerohr** [comment]
Since this is changing API anyway...

I'd prefer what the `table_name()` static method would return in SS5 - `VendorBasename` - e.g. `SilverStripe\Assets\File` becomes `SilverStripe_File`
and apply that to all three.
Could have a `GraphQLSchema`-like class to build these definitions.

I can see the benefits of having plural and singular to build a descriptive API, although to me it's more clutter and complexity than necessary - as I've experienced when building a scaffolder on the javascript-side to mirror the PHP-side's scaffolding https://github.com/flamerohr/silverstripe-graphql-react-boilerplate/blob/master/client/src/js/lib/graphql/updateMutationCreator.js#L32

**Comment by unclecheese** [comment]
New output per [PR](https://github.com/silverstripe/silverstripe-graphql/pull/143) ignores `singular_name` and `plural_name` in favour of a custom type naming API. Defaults will first use `table_name`, and if not defined, use `ClassInfo::shortName()`.

```php
<?php
namespace MyPrefix;

class MyDataObject extends DataObject {

	private static $singular_name = 'Data Object';

	private static $plural_name = 'Data Objects';
}
```
* Type: `MyDataObject`
* Query: `readMyDataObjects() with readMyDataObjectsConnection, readMyDataObjectsEdge
* Mutations: updateMyDataObject() with MyDataObjectUpdateInputType, deleteMyDataObject()

```php
<?php
namespace MyPrefix;

class MyDataObject extends DataObject {

	private static $singular_name = 'Data Object';

	private static $plural_name = 'Data Objects';

         private static $table_name = 'DataObject';
}
```
* Type: `DataObject`
* Query: `readDataObjects() with readDataObjectsConnection, readDataObjectsEdge
* Mutations: updateDataObject() with DataObjectUpdateInputType, deleteDataObject()

```yaml
SilverStripe\GraphQL\Scaffolding\Schema:
  typeNames:
    MyPrefix\MyDataObject: UncleCheese
```
* Type: `UncleCheese`
* Query: `readUncleCheeses() with readUncleCheesesConnection, readUncleCheesesEdge
* Mutations: updateUncleCheese() with UncleCheeseUpdateInputType, deleteUncleCheese()

**Comment by chillu** [comment]
Looks a lot better! Is there a way to set a custom plural name? That's going to be important for any case where the poor man's pluralisation in core doesn't work (many English nouns and pretty much all nouns in other languages).

**Comment by unclecheese** [comment]
The only time the plural name is used is in the `read` operation, which means there isn't a good case to increase API surface to support it, IMO.

```yaml
My\Namespace\Ox:
  operations:
    read:
      name: readOxen
```

is just as much effort, and more clear, if you ask me, than:

```yaml
SilverStripe\GraphQL\Scaffolding\Schema:
  typeNames:
    My\Namespace\Ox:
      singular: Ox
      plural: Oxen
```

**Comment by robbieaverill** [comment]
Using `$table_name` seems wrong to me, because that config prop represents an underlying database structure. I think it would be a dangerous assumption to make that it's always doing to be something human legible.

For example, when it became a _requirement_ to define a table_name in 4.0.x we added psuedo namespaces to the silverstripe/elemental-blocks module, seeing as they previously would've been FCQN's translated to MySQL table names so we followed suit and made them something like `S_EB_BannerBlock` to keep psuedo namespaces and minimise chances of conflict in "BannerBlock" tables with other DataObjects.

I'd much rather we add a new API for this, like `$graphql_scaffolding_name` or something, then fall back to `ClassInfo::shortName` if not defined.

**Comment by flamerohr** [comment]
I agree with @robbieaverill, this would be better off as a different config option rather than coupled with `$table_name`
It's for a different purpose, although can be seen as very similar.

**Comment by unclecheese** [comment]
There is a new API for it, as illustrated above. The question is just how robust the defaults should be. `ClassInfo::shortName()` is not a great fallback, because without the namespace, you can easily run into collisions. `table_name` is guaranteed unique.

**Comment by unclecheese** [comment]
The only alternative I can see here is that we enforce the naming of the type, which would really degrade the developer experience. Using only `ClassInfo::shortName()` to compute the default seems dangerously fragile to me. There just aren't many options at our disposal for generating canonical names of dataobjects. `table_name` is flawed, but it's decent.

**Comment by robbieaverill** [comment]
I'd probably prefer to fallback to a sanitised FCQN instead of table_name, e.g. `readSilverStripeBlogModelBlogPosts`. It's nasty, but is still unique and would ensure that devs see that if they want to make it better that they can customise it with config - it does bring up the same discussion we had last week @unclecheese about exposing system internals (namespaces).

Either way I don't think it's safe to use table_name for this purpose

**Comment by chillu** [comment]
My take on this was "make it consistent and predictable", which would be fulfilled with the FQCN that Robbie suggests. I agree that it's probably a safer default than `$table_name`. If devs don't like the FQCN notation, they can opt for the `singular` and `plural` YAML config options. All of the above is better than the random camel vs. snake casing that we had in the initial bug report here :)

**Comment by unclecheese** [comment]
The good solution would be to prefer shortname when possible, e.g. detect collisions, and fallback on something more verbose. But I guess that would violate the "consistent and predictable" goal.

**Comment by tractorcow** [comment]
PRs need fixing before they can be reviewed sorry @unclecheese .
